title: Markens

# Settings
exclude:
  [
    ".github",
    "Gemfile",
    "Gemfile.lock",
    "build.sh",
    "build-and-serve.sh",
    "build-and-watch.sh",
    "README.md",
  ]
permalink: date

#remote_theme: pages-themes/hacker@v0.2.0
#theme: hacker
plugins:
#  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-redirect-from

relative_links:
  enabled: true
  collections: true
